---

services:
  backend:
    build: ./backend
    container_name: pong_backend
    restart: always
    env_file:
      - .env
    expose:
      - "${BACKEND_PORT}"
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - ./backend/migrations:/app/migrations
      - ./backend/static:/app/backend/static
    ports:
      - "${BACKEND_PORT}:8000"
    command: sh -c "/app/init.sh"
    networks:
      - transcendence_net

  frontend:
    build:
      context: ./frontend
#      dockerfile: Dockerfile-dev         # uncomment this line if you are Alex
#    volumes:                             # uncomment this line if you are Alex
#      - ./frontend/src:/app/src          # uncomment this line if you are Alex
#      - ./frontend/public:/app/public    # uncomment this line if you are Alex
    container_name: pong_frontend
    restart: always
    ports:
      - "${FRONTEND_PORT}:3000"
    depends_on:
      - backend
    networks:
      - transcendence_net

  db:
    image: postgres:17
    container_name: pong_db
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - transcendence_net

  pgadmin:
    build:
      context: ./pgadmin
      dockerfile: Dockerfile
    container_name: pong_pgadmin
    restart: always
    env_file:
      - .env
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - transcendence_net

  nginx:
    image: nginx:latest
    container_name: pong_nginx
    restart: always
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/ssl/certs
      - ./backend/static:/app/backend/static
    networks:
      - transcendence_net

volumes:
  pgdata:
  pgadmin_data:

networks:
  transcendence_net:
    driver: bridge
